site_name: Pergamon Technical Documentation
site_url: https://projectpergamon.org/technical-docs/
docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - Specification: spec.md
  - Vocabulary: vocabulary.md
  - Validation: validation.md
  - Standards crosswalk: crosswalk.md
  - Example: example.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    
extra_css:
  - stylesheets/pergamon.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

